name: token_bloc
description: A library that helps implement the BLoC design pattern with the power of Dart Stream extended by the capabilities provided by the RxDart library.
version: 0.1.1
repository: https://github.com/alvarobcprado/token_bloc/tree/main/packages/token_bloc
issue_tracker: https://github.com/alvarobcprado/token_bloc/issues
homepage: https://github.com/alvarobcprado/token_bloc

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  meta: ^1.3.0
  rxdart: ^0.27.7

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
