name: token_bloc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ">=2.17.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  meta: ^1.3.0
  rxdart: ^0.27.7

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
