name: flutter_token_bloc
description: Set of Flutter Widgets that make it easy to implement the BLoC design pattern with the TokenBloc library.
version: 0.1.0
repository: https://github.com/alvarobcprado/token_bloc/tree/main/packages/flutter_token_bloc
issue_tracker: https://github.com/alvarobcprado/token_bloc/issues
homepage: https://github.com/alvarobcprado/token_bloc

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  token_bloc: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

